import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Provider from "~/util/provider";
import { Toaster } from "~/components/ui/sonner";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "TheMessCompany",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
  weight: ["400", "700"], // Specify the font weights you need
  subsets: ["latin"], // Specify the subsets you need
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className={inter.className}>
        <script
          type="module"
          defer
          src="https://cdn.jsdelivr.net/npm/ldrs/dist/auto/spiral.js"
        ></script>
        <Provider>{children}</Provider>
        <Toaster />
      </body>
    </html>
  );
}
